### ISSUE TITLE
TypeError: write_stats() got an unexpected keyword argument 'datadfs'

### ISSUE THREAD

**Issue by mroosmalen** [wdecoster/nanostat#10]
Hi Wouter

I try the run the following command:
`NanoStat -t 4 --fastq reads.fastq.gz -o outputdir`

But I get the an error:

```
Traceback (most recent call last):
  File "/hpc/cog_bioinf/kloosterman/tools/NAP_v4.0/env/bin/NanoStat", line 11, in <module>
    sys.exit(main())
  File "/hpc/cog_bioinf/kloosterman/tools/NAP_v4.0/env/lib/python3.4/site-packages/nanostat/NanoStat.py", line 81, in main
    outputfile=args.name)
TypeError: write_stats() got an unexpected keyword argument 'datadfs'
```

Can you help me?

**Comment by wdecoster** [comment]
Can you make sure that the nanomath submodule is the latest version?

    pip install nanomath -U

**Comment by mroosmalen** [comment]
Thanks, this solved the problem

**Comment by wdecoster** [comment]
Good to hear. Please let me know if you encounter any problems or if you have any feature requests or suggestions.
