### ISSUE TITLE
TypeError: get_input() got an unexpected keyword argument 'barcoded'

### ISSUE THREAD

**Issue by mw55309** [wdecoster/nanostat#11]
Any idea what's going on here?

```
$ NanoStat --fastq MinION_chicken_ceca/MinION_chicken_ceca.fastq --outdir test
Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/nanopack/bin/NanoStat", line 6, in <module>
    sys.exit(nanostat.NanoStat.main())
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/nanopack/lib/python3.5/site-packages/nanostat/NanoStat.py", line 73, in main
    barcoded=args.barcoded)
TypeError: get_input() got an unexpected keyword argument 'barcoded'
```

??

The run isn't barcoded

**Comment by wdecoster** [comment]
Could you please check if you have the latest version of NanoStat and nanoget?

**Comment by mw55309** [comment]
So I just installed using conda (pip install failed).

Running a conda env with python=3.5

**Comment by wdecoster** [comment]
I'm on teambuildingsweekend with colleagues so will help you later. 

Can you give me the output of 

python -c "import nanoget ; print(nanoget.__version__)"

**Comment by wdecoster** [comment]
Should have been `__version__`

**Comment by mw55309** [comment]
0.15.0

**Comment by wdecoster** [comment]
That's pretty old, https://bioconda.github.io/recipes/nanoget/README.html

**Comment by mw55309** [comment]
OK, but I guess this is the version installed when I installed nanostat....

**Comment by wdecoster** [comment]
Possible, will check it later, but now you could already conda upgrade nanoget which I believe is going to solve the problem

**Comment by mw55309** [comment]
Hmm, I am less convinced this is the problem

```
$ conda upgrade nanoget
Fetching package metadata .......................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/nanopack:
#
nanoget                   1.5.0                    py35_0    bioconda
(nanopack) [mwatson9@login04(eddie) ~]$  python -c "import nanoget ; print(nanoget.__version__)"
0.15.0
```

**Comment by wdecoster** [comment]
This suggest that you already have another nanoget installation, which is earlier in sys.path.

Can you check

`python -c "import nanoget ; print(nanoget.__file__)"` which should reveal the path to the installation directory, maybe from pip?

**Comment by mw55309** [comment]
You're right, it was from an old version of NanoFilt

Does the conda recipe need updating to specify a version of nanoget?

**Comment by wdecoster** [comment]
Yes, it does. I'll go over the recipes and update the minimally required version. Thanks
