### ISSUE TITLE
Wrong stats

### ISSUE THREAD

**Issue by haowenz** [wdecoster/nanostat#17]
Hi,

I tested NanoStat on my toy example and got wrong number of reads. It seems that other statistics are also wrong.

Read files:

> >ERR764952.1 channel_100_read_97/1
> CCAGTCTGCTTACTGTTATACTGAGTCGCCTTCGGGTAGTAGGCATGCCACTAACACATTGTTCACCTGCGATTAAGAACCAGGGCTCGAACGTGCAGCTGCCTGGCCAGCTAAGCCCCGCTTGCAGACCGCGCCCGGCCTTCGCTTCAACCGCTTCAAAGATACCCCCGTTCTCGTTTGGTCAAATCAACAATTTCTACCTGCTCGTAAAACTAACACAGGAGTAAGTACCCAGCGGCGGTGACTCTACACCAATGACTAATAACCAGGTAGGTTACACCAGCTGGCTGTTGCTTTCAGTTCCGCAACAGGTGTTGGATGAATGATATCCAGCGTACCTCCCCGAAACGTTTTGTTTTTGTCACTCCCGGCTTTTCAGCACTTCAGCAGCGTGAATAGTGGTGTTAACCGGGTAGTGATAATGAATGCACATTTCGGGCAGGTTTACGAAATTGGTACCGAGGTTTTCGCCGATGCCGTGAATTTTAACGTTAAACAGGTCGGAACACCGTAGCATACGCAGTTTACCGACTACGCTGCAGAGAGGCCGCAGAACGACATCTGCGCCTTCCATAGAATCGCATCTTTCACAAAACCTTTATCTTTACAGCAGTAGAAATGGCTCAGGTCAAAAGGCTAGGGACGGGAATCCTCCAACGATATCATGAGAGTTGTCTAAACCTGAAGGCAGTTGGGTTTTTAACAACAGTAGTGCGGGCGAACCGAAGGGACAAATGGCCAATACCACAGCAGCACGAGGACTGCATATTTCAAGGTACATATCTCCTCTTATTATTAAACTAGATATGTTGCTCCTGCCCATATTAATCCGCTGCTTGCTAGGCGTTTATAAACCCATCTCGAATGTGATCGCAAAGTTCTACCGGCCGTTTATTGAAGTCGGATTAATGATCAGGAACAACTTATAGTAATGCTCGGTCGCTTATGCATTATCAAGAAGCGTGTCACGGCTATCTTATAAATATGACCTACCGTTCAGCCGACCCTCGTAATTTACTGGGACAATTAATTTATTTTAAGCAGTTGCATTAATCGCAGGCATGTTCTCAACGAATTTGATAAAATCCGCTCTTTCACTCATTATTTCAACCTTCTTCGACAAACTTTCCCATAAATTCAATGGTATGCGAGTAATGTTGTATCTGCCGGCTAGCGGCCCATATCAATATGCGAAGCTCGGCTAAGCGGAGGACCACAGTCCCTACCAGCTTTAGGCATTACTTAGAAGAGAATTCTCTATGATCCCAGAAATCGTCGCCGCATTTTGCAAGGAGCGGATTGACATATTAATCAGTCTAATCTCACAATGTTATCGCCAAGTTGGTTAGCTGTGTAATCCCACATGTCGCACTGAAACGTTACTGCCTGCCACATAACTCGCTCTTACCAACCACCTCCGGTTCATTGAAGAATCTGGTGCTCATCATCTAATGAATGCAGTTGATTCATACCAGCCTGGCGCGCGGCGCAGTTAATCCCCTGCTCTGACCACTGGGCAGGGCGAGGTATTCTGGGCACAACCGCTTATCATCCCCATCTTTACCGGCCTCCGTTTCAGTCGGACCTGTATTAGGCGGCGTATTTAGAGCTGTCAGCGCATTCAAATCTCTGATCCCCGTCGTTTCTGACGGCGGGAGGAGAAGGAGAAGGAGGGATGTTGCTTATCCTGACCCCCTGCTTTCCCTGCAATTTAATTTAACGATAATCCGTTTTTACTGCATGTCGACTTCACAATGAATACATAGGTAAGGCGGCCGATCAAGGTCCGCTTATCTAGTGCAAAAGCCGATTAACGATAGTAACCGTATTCCTCGTTATTTTTGTTGGTCTAGGTCCCCTTTTAGCCTTAGTAACCCAAACAGTCTCCCGGTATTAGTCACTCATAGATCCTGTATTATTTTGTATGACGTACCGAAACAGCCCAGCTAAAGATTATGTCGAGCCTGCTGAAAATCAAAACCACTGTTGCTATGCATGCCGTACTTTCTGTTCTCTTTCACCTGCATTCACGCTGCCAAACGATCATGCTGCACGAGCACGGTAGTTAGCAGCATGAGGCTCGTGGTATCCGTAAAATCTTGGCGTGTGCCCAATGAAACTGCGTGAATTAGGCTCCAAAGGTAGAAGAGAAAGAGAAACTGATAATAGTAAGGGCGTGAGAAACTGATAAGTAGCGTAAAGTAATAGCAACGGGATGGATATCCGGATACATCCCTCATCGTCTTGTCCCTACAATGCCCCCGGTTCACATTTTGCTAATGACAGAACACTTAAACGCAAATTAGGTTTCGCTACTCTTCCTCTGCCTCATCGACCCGATTAGTACCCACGGCCATATGAAGGCGTTCTCCCAAATGAACAAGTTAAATCCCTAGTATGACGGGGACATCGTCCTTGCTCCCATCCCGACTTATCCGTGGAGGTCGATCCTTATTTCGCCAACAAAATTTGGCTAGCACATTACGATAAAGTTATACATGGTAAGTACATCAAATCAATAGTATTCATCTGTTGCCCGTCACGTTCGCGGCGCGGTGTTATGCGTCCATCTAAGTAGCCATGAAAAACCGACATTTTGGCGTCGGTTTTTGATCAACTATCATTCAACGCATGTTGATACTTATGGAGCATCCCCACAGCCGATTACCGTCGTCACTGCGGTGAGTTACAGATGCATGATTTCAACTTAATTCCAGTTCTTCCGATAACCACAATACCCCGACGTTTATCATCGGGCAGATGACAGGTATTGCTGTGCATGGAGTTGTCGGGCATGGACAAGAACGGACTACCGTTTTAACTCTCGGATCGGTGCATCACGGAGAAGGCATGGTTGGCAATAGTATCATCGTCATAGCGCCGAGCAGTGGTTTAGGCAAATCTACGGCTGGAGTATTCATCAGCATACATAGTGAGTAAATCCGGGAGACCTTCTCTTTGGAGGTTGCCACATTGGGTCATCGCGGAATAGGACACCGGCGAATAAACTGATTAAGCATCCGTCCGTCTTCTTACCGCGATTTGCACCAGAGAGCTCATCCGGCAGCGCAGCTACGATTTGCCTAATCCATGTCAGAAACTGAAATGGAGATCATCGTATCCAGCACAAGCCTGGTCTTATTGATATGAGAGAAGTCCCAACCCAACGCGATCGCCGTTCTGTATATTCAACCAGGAGAATCCCAGCACATGCACCAATCCAAGGGGCTCATCCTGTTGGGTTAGAAGCTGTAGAACCCAGCAGCCATACTGAAGGGAGACACGTCTCCAGTAAACTCCATTAGGGTCGCCACCATTAATTAATTCGCAAACGATTGCGAGTGACCTTCGACGAAATCATGACAGGTCAACCGCCTGCCAGAAGTTACAGCCCGTCCCAGCCGAGAGACGATTGCCCGAGAATGCAGGAAAATGGTTGGACACCGAAGTTACCAATGCATGATGTGACGTTCAGTATGATAATTTATTCGCATTTCGCCTTGCGATCTCTTCGTGCTTGGCGTTGTGATTTTGTTGTGTGTGTACTGAGCCCCATCCAGAAGCTGATAGCGTTGCGCCGCAGCTCGAGACATAATGGTAAGGCGGAGTTTCCGCGTTCTTCCCGCATTCCCGGCGAGCTCTCCGCAGGCGTTTAGCTGCGTAGCTTCCTGCGGGATTTCACCAGCGTACGTTAGGGGGTGGTGACAGTGGGCCAATTCCAGTGAGTTTTACCGGAACAAGGCAAGTTTCGCAGGATTACTATCAGGACAGTCGAGATAGAGTATTGGGCCTTTTTAGACGTCAAACCCGCGCCCAGCGGGAAGCGTTACAATTCAATTGCTGCGCATGCCTTACCACGTGATGCGTCGCGCAGGTCGAAGCATTTATCACCTATATTCACCATCACATGCTTGATCTCGAGATCCATTAATTAGTGTCGCAACAGCGGACTTTCCAGCTCAAGTCGACATTCTTTGATCGATCTAGAGAGAGGATCCGCCATAATCGCACACAATACCAACTCGATCTCCCTACAACGTTCGACGCGACGATATTATGTGAAGCGTAGGCAATCGTTTGGCTTTCTCGGCTCTGAGTGGTGGTGCGAGTGATCAGCGCATGACCGTGCGAGCCAGCCCCGCAACCGAGTTCTATTCGTACCAGCAAAGGAGTATCCGAACTCAAAACCAACCCAATACAAGCACACCGAATCATCAATAATGGTTAGGGATCGTCTAGAAATACTGATCGCGGTTGCGCCGGACGAACAATACAGCCAGCCTGTGCTCCTTATGCGCGGGGCCCTAATAGCGAACGATGGATTTCTACCTCCCGCAGCAGCCAGTACGGCGCAGCCGGGCCGGGTCAATCTCGCCCGGTGAGCGTTCGCACTGGAAGTGAAGCCAACAAGCACACACGATCAACAATGGCGGTCGGCGTCTCGCCCAGCCGAATATGTTGGTTATGCGAGTGAGAGAGATACCCATCGTGATTAACCAAACGCAGAATGGGCCGGTTTGGAAACGAATCTGCTCCTTTCGTCGCAGTGAGTCTGTTGCTAGTACTAAAGTGGCAGTGATTAGAGAAACAGATGTTCTCTTGCTGATGTCCGGCGTATAGCGAACCACAGCCGTTGCGCCAGCACCGCATTTCAAGGTCAGTCTATTACCATCCTTTGGTCACCCGTGCTGCTGGCGTTGGTACATGCAGGCAACACTGACGGCTTTATTTCGCTATTTGTTACTGCCGGGGGCGTATTCTCTGGGCGCGCCATCTCCCCGACTAAGCCATTCCACTTAGTTTTATCTTCCAACTAACGATCACAGGATTTCTGTTACCCGGCGCAACCACGTTGGTGTCTGGAATAAACTCACCGGTATAAACGTTTGCAAATTGGTCGAAGCCATCTTATTAGTGGATTCTGGACGGTCCGTTCGGGACCTTCACAGGTTTTTACGTACCTGTGTCTATTCCTGATTTTCACTGGTAATGCAAATCGTTTGTAATCGCTTTGTTGGCCTCTGGTCACGTGGTCTCTTCACATCACGGGCACACCAAGCTTTACACCTTCCGGCTCCAGTTTCTCCTGTTGCGGTACCTGATAGCCCAACATCGCTTGCACTTCGGCGCCCCTTTCTTTTCACCAGTAATTGTCGCCGCTGGCTCCTTATCTTATTCCTTTTCACAATATTGCTGAACACTTCACTATACTATCAGTTAGAATCGTCCGGCGCAGTCACGAAACGACGTCGGGACGGGGCCGGAGTCACCGTTTCCAGGGAATTCAATAGTTGTAATAGACCCAGGCAACGTAATTGGCAATGAAGCCACCACCGCCAGTGACAATGAACGTGATGGGTCCTCCTACGGGAGTTTCTTATTAGTGTTTCATTCACTGATACAGCTGAAACAGTCGCGATACGGCCACTCCGGCGCAGCAACAGGCGGTGTTGTGAACGCCGGGTGCCAGACAAGTCGTAATGTAGCTGTTGGATGGGGCTAGCGGTAGCCCGCAAATCGCCAGTACTCCGGCAATTCAAAATATCGTGGAAGGGCGGCCCCCGATAACGGGAAACAAATAATGTTGGTATTGGTCTTGACACGAGAGAGCAGGCGTTATTATTTCAGCATCTGTCTCCCAGGGGGCATGGAAAGCCGGGCGCAACATTCCTGTAAATTGATGGTTTTAGTATACGTATGTTATTAGTTTATATTACTTGATCCCCTTACTTTTAGATTGTGGACGGCTGCTGAATAATTAGAACCTACCAAAACGAATGTCGGTTTCAAGGGTAGTTGAGTTTGGCTCTTTTACGCCGCCGCCAAGCTAGCTACAATGAGCGTTTCGTCCTATCAAGTCAAACGGTACCATATCTGGAAGATGAGTCCGAGATAGGCTGTTAAACCGTAGCACTACGAGCATTGGCTAACCCGGCCATGCCGGAGTTATAACACCAGGGCTGCCGTCATCCTTCATGAAAATCCAGGATGTTCTGAGCGATATCTGCCTTCACCTGGACACCAGATGAGCTATAATACGCATTGACATGTTCTTCAACTCTGTCTGGCACAGGTCTTTCTCCGGGCTGACAGCCGGATAAGACGTGGGCTGGGGCGGGATCCGCAGGTTTACGTCGGGACGGGACGGGACACCTTGGTTGGCTAGGAGTTCCAACGCAACTCTGATTAGAGCTTCTGGATGTGGTGAGTTGTGCCGTCAGGGGCGTTGCAGGATTCTTCACGACCTGTTCCACACGTCTGGGCGCCGCAATTGCCAATGGTATGTGCCCGAGACATGAGCTATCTCACGATACAGCATACAGAAACCACGATTCAGTAGTCATATTCATGTAACATGCGTAAGCGTGCGTGGGATAATGAATTTGAATCAGGCGGGGATCTCAACGCCTGATCCCTAAGGAAGATTTGTGACGGTGATGCATCCCTGGTGCCTGGCTGACAGGGTGCGGGATCACAGCGTGCTGATCTGATCATGATAGGAAGTCAATCGTGGCGGAGCTGGAAATCCTGCTGCCGCGTTGAAGTCAGGTCACCTCGCGCATTTATGCGTTACTCTCCAGGACCTAGCGGCTTAAGCGCTGAAGGTACACACATTGGTGCTGCCGGCTCCAATTATTTTTGTTACATGCTGCGTGATCGTGTTCAGGAGAATGCACGGGCACGGGAGCGAAACCGTGCTATATTGATTCTCGTGTACATCTCCTGTGCCAACAATTCCCCTCCTCATCACCCCAGCGCGGAGCCCGTTCATAGTTAAATCGCGACAGTGATCCGTGGTACTTCTCCAATAGTGAAATTATGCTCGCAATCGCCAACAGTCTAAATCATATTTCGACGTTGGCTGGGCCACAAACCGGCGAAATATTGCCTGTTACCACGCAGCACCCCACGTTATCCGTTACATTACGTGCCAACCATCGAAATCTGCTGCGAGCTGGTTTCCGGGCGGTACAATCAACGTTGGCCCCTTTCACCGCCTTCGTTACTTTACCGTTCAATCAGATATGCTTCTGAAGTACGAATAGGAATTCCAAGAGGTGATATCCACCTGACCGCCACCATTTCGGTGCATAGATCGATCTCAACGATTCAATTTCATGCGGGATCGATTTATACCCGGCGGGGTAAGGTTGGTCATACGCGGCATGGGCAGATGGGCGTAGGATTCAGGCGACCGTTGCCAGTCAGTTGTCGGCTGGACGCATCAAAACGCGCGTTGGGAGTTATCCTGCATGTAGCCTTTCGAGTGCGTTCTCAATCAGCGTTTTGTACTGAACCGTACTTCGTCATCAATCAAGGGGAAATCGGGGAGTGCTGGCCAAGATACGTTAAAAAGCTCCTACTAACCGCTGCCCGTTGGCGGCCCGGGTCTCACGCATACTGTCTAAATACTGAAGTGCTAAGCGGTCGAAATTTACCTGTTCCACCAGACCGTACCGGCCATTCGATGCTTCATTGTGGAAGGCTAAGGCCAGGCTCATGATCTCCTGCACAAATACTACAGGCATGGTGCCCTGGTGCGACAGGCCAGGCAGATTGTGAGGGCGCCATACGCCATCCTTCTTTTGCCCATTGAATGGGCTAGGGTGCCGTCGAAGGTCATGAGGAGAATTCAGCGAGCTCACCACTACGCCGCCTGGGCACCCGTTCGCGTTTCCATCTTTATTCAAAACGCAGGCCTCCACACGAGAGAGGCACCAGCACCTATCAAAGGGCCGTCCTTCGTGGCTCACAGTATCACTCAAGACTATTGTCACGTTAGACTGGACTATCGGATAAACCATTCGTTCTCTTGGCCTATTCTTGTCGCCTTCGCGGGCTCGTATTAGGCGACGAGGGGTGGGGCACTTCTCTTCACAACATGCTTGTTGCAGCGGAGTCACCGAGGTACAACGGGCTATGCTCTACAAGCCCCCGAGCGTCTGTACTTTACATCACGCTGACGGACTAATGTCTGGTGCCAGAATGCGCACTCTGTTCCACCACGAGCAGGCGTTTGGTCGACAGTGGTGGGAGAGATACCGTTCTGTTTATG
> >ERR764952.2 channel_100_read_98/1
> TCTGTTATGGTCCAGCCCTATCGGGTTAACATGGCTCTCCACGGTAGCTGCATGGATCGTAACCGTTTCCGCTTTGTAATCAGGTATATATGGGCCACGATATGACACCTTATCGACATACTTAAATCGGAGCGTAGGACTGCGTGAAGGTTATTCATTCGACTTGCCCCCTCATCAACTGGGCCAAACCGCAATGTTTCCATCCCATCCATCACGCGCCGATTATTTACTTATCGCGTGCCGACCCCATCCCATTTCTTATTAATTTCTACTCATCGACGAAGGTGCCCTCTATTTGCTCCCTCAACAACCAACTATCTTAGGTTCCGTAATCCAACTGGTTTCTTCTTCTGCGTACGTTCCCCAGCATCTAATAATTTCGACAATTGTATCACATTGTTTGTCAAGTTTACCGTATTTTAACGAACGTGCGTCTAGCGTCTTAGACGTTCAGTAACGGATTCCGTTTCATCACAACCGTAAACATGTCTCAAATCAGGCGGCTGACATAATGAAGGCTCCGAAATTAAAGGGTAACTTTCATTGAATCTCCTTATAGGCCCCACAATAGGCTAAATCCGTAAAACCATCTGCATACTACATCTCAGTCGCACCTTTCTGATACATACTGTCACTTGTTATTATTAAGATAAATCGTCCATCAGGTGTGCCAGATAATCATTCACGTATTATCTTTATTCTTACGATTTTATCGCTATGCGACACGTTAATACGGTAGAACTATCTGCACCGTGAGTAGCTCGCAGCAACTATCTGTACCTGTGGACATTCTTCAGAGGATATACTCTCCTTTCTTAATTATCAGTTCTGCTTAATGCGGATATTTTCTCATTAATCTTTACAGACAATACGCACAATTCCATATCATTACACCAGTGTGACTTCTGCGTTTCTTTCGACGAACCTACGAAGAAGTATATATATGCAATCTATCAGTTATTATTTAGCTTATACGTACAGGGAACACCACAAACGTCAGAATCCACTTAACCAGATCTGGCATCATCCGCGTATCTGGCGAAATAATCCCGACAGTGTAGATTGTTGTAACCTGCGGTCGCAACCTGATAGTTCACATCCGGCCATTTCAACCCGCATCGGGTTAACAGCCTCTCCCCCTGCGGCGTACTACGTATCTAAATCGCTTTATAATCGGATAGTTCGGGACCGGTACACGTAAAATGAAGCTTAGGCTGATACGATGCAAGGTCTCCACCTCTACCATTAGACACTTGCCCCATTCATCATATTCGCGCTCCTAGTGGTTGTCAGTCTTCGGACCGCCCCCGGAGGAGCATTGGTCGCAATCGCTAAACCCCTTTGTTGAGGCGCCATGTGTAGACTTCAACATAAATTTGGCCAGTTAACCACCGTCAAGCCGCACTGCGCAGCGCATTTCATGCTCGCAGTCTGCCGAGATTTCTTCCTCCGGGTGAGCAGCCGGAGGCGTCATAGGCGGAGAAGCGCGTGGCCGTTCTCATACAGGTCCTGCTGAGGCTTTATGCGATGAACCCCGGGCCGCTTTTCCAAGCCGTTCTCTGTCTCAACTCCAATACCATAAGCGTCGAATTCCGATAGTGACCCCGTCCCGTCTAAACCTGTGATCATTATCGCACGTCGTCAGCCTGTCTCCGTCTAGCCATACCCTAGTCAACACATTCGCAGCGCCCAAGTAGGCCGTCTATTAGCTTAGACGCACCCGTTGCCATTCGCCGTCCCGGGACGTAGAAGAAAGCACCTCCGACCGTAAGCCCCGTAAGTGTACGATTGACAGGCCCAGGCGTGGACCTGTCGTAGTATAACTCGTATGCGTGCCAGAACGGTCGTCCGTCCGTATCGCCCCACGGATGCGGTCGGTCTGTTGGCTTCAGCCTTAAGTATTCATCGTGGCAGTAAAAATCCCATCCTCCGCGTAAGTTATCTAAAAGTGAGTGTACTGTCCTAGACTGCGGCCCGATGTGGCAGCCCGGTCCGCCACAATCCGTGAAGCCAGGATGGGCAGGTCGAAGTGGGTGCGGAGGGACCGACCCAGCTGCCATTAAGTGACTAGTTCGCGTCTGTCACCGAACCGAACGGCGCACCATTACCGTTACCTCCCACCGTAGTCACGTGGGTCGCAGAGGCGTTCAGTATGTATATCAGCTGGTATACTCTCTCCCTATGCGGGGAGGAGAGTGGTGGTGTCAATTCGTTAGTGAGGCATTACTGCTGCCATGCTGCCGAAGCTGCAAGACAGTCTCTAAATCCGTAAAGTTCCAGTACAACAGGCGTCAGGGGACATTCATTCCCGCACTACCCGTCCACACATACGTCATAAAACACCGGCAGCAGAGGCTGTTCCCGTACCCATTTTGCAGGCCCCCTGCTCGTTTTGTATGCAGTGTCGTCTCGTAATCGAGGGCGTCCGCGTCTCCATTGCACCGTCGCATTCGCCATTCATAGGCTTCTCTCCTTCGACACCCATAATCGCAGCCCGGTACATTCAGACCGATAATGTCTGTCGAGCACAAGTACCTCCATCATACTTATGACCCTATGCTCTGCCTTTCACGTTCGGTGCGGGCTGATACATTCCCGTCATCGTAGTACCAAGAACTCCCCTTAGCGTAACTACACTCTGTGAGTTCCGCGGTCAAATCACTGATATGTTGCGTCCCCGTCGGGTAGTACCAGCCGGATTCCACGCATCATGGGCGCAAGCCCTGTGACATGCCGTTCTCCGCCGGTCTTCAACGGACAATACCGTCGGGACGATGTATGCTCCTTGTGTGTACCAACTACTTACGTCATGCGTGGTGCTAGCCGTTACAAGAAACGTACTCTGTGTCTTGTAAACCATTTGCCGTCCCATAATATAGGCATTCATTACATGCGGCGTTATTTCAAGCCGCGTTTCTAGCTGTGCGTGTTGTGTAGCAGATTAACCAGCCACGGTTGCCCCGGAACGGGGGCTGATGCTTCTAGACGCGAGGTCACTCTCTCGCGGTCATCTCCCCCGAGCATTCTGTTAAACGGGTCTGGTAGCCCGAGCAGTCATTACAACGCACAGATTAGAACCATCGAAAGTCATCTGCCAATGCTGCCCTTCCAAGATCACCGTTGTCGTCGCCAACCTCCCTTGTGACCCGGTGATACCCATCCTCCGTATGTCTCCCGCTGCGCGATGTCTCCGATACCGAGCTGCCCGTCATCAATTCCCGGCACTGAAATATCTCGTTTACTACCTCTACTCAGCCTACTATTCTGGACTTTCCCGTCGTTGATAATTTCGTCTCCCGCGTCCGCTTGTATTTAGTCTATCGTCGCCGACACGATTCAACCGTACTCTGTCTCTCCCCGTCCCCCGTTATCGTCTGCTAGTCAATTCCTGCCGTCAACGCTGCTAATCCTCGGGCCGTCACAGTTCTTCTTTTTCGCCCCGTTTCCTCCCGGCCGCCTTCTTATCCAGCACCGGTCGGGGTTGATACACCTATAATCCGAATTGGTTTGTGATGCTCATCACCGCCTCATACTGACCTTAAGGTTTCAGTTGCTCCACCACCCCCGTATCGTCTGACAAATCTGGAGTACCGGCTTCGCCAGTACTGCCGCCAGAGTGGATGGCCAATGGATTGGGCCGTCAACCTCGTGAAGGCCCGGGGGACATGCGTATTGCTGCGGTCACTCCACGAGAAGTCCTCGAGCTTCAATCTCGTGTAACAGAGGCGTACCGCGACGGGCAGGCGACCCATATGCGCGGGTGCATCAGCGCCGAACAATCGCCATGTCACGTATCTTCGGATGGCGGGCAGTTGGGGAGGCTGAGGCGGCGCAAAAGGGCTCAAAGGGGGAACTGTCGAAGAAAGACGAAGAGTGTAAGTAATAACGTTCGACTACATGCCTTAATCTTGGTCAGCAAGCGAGTACCCGGCGCCGTCCGTCACCATAGTGATTTCCCCAGGCATGTAGCGGGATAGACAGTACGTCAGCGTCCCCCGAATCGGCGGTTCCCCATCCCATTACACCCATCCTGAAGGAGCACCATGGCAGTACGTCGCCTCACCCCGGCACCCGATAACAAGCCCCAGTATCCACCACAGGCCTGTGCCTGTTGGTCCGAGAGGTAAGGATGCATGAACCAATATCCGGCGCAAAAGACACCCGCGAGAGGCCGCGCCGGGACCGTCTAGTGTGCTGCTGCCCTAGAGCAGCCATTATATACCTTAAGCTGTACCTAAGCCCCCGGCAGCAGCACTCAGATGCGTACTCCACGTTGGTTTGAACTGGTAAGTCCTTTGATGGGGGTCGTAACCTGTAAGCACAATATCAGAAGGCATTTCCAGCCCACCGCAACGACAGGGCTTGCAGGCGTCTTCGTTCCGGTAGCTGCTAGTGTAGGTGCGGGGAGAAGTGGAGTGAGTCGGGCGGGGTGAGAGAGAAGGAGATGCTTCCCCCTGAAGCGGCACACCTTCGCCCCCAGCAGCGATTTACCGGGATTGCCCGAATCATCCCGCCCGGGACGCCCAGCGCGCCATTGGGAGCGCCGTTATTTGACAGCTGCCGAACCTGACACCTATCAAAGCCCCCTCTGAATCATATCTAATCTCCCGCCTGGTTCCATCATATAAATCCACTTTTAATTATTTCAATGGGACGGGGCTGTGCGTTCCGTTGTCGTCGTC
> 

Output from NanoStat:
$ NanoStat --fasta my_test.fasta 
General summary:	 
Mean read length:	3202.5
Median read length:	2359.0
Number of reads:	4
Read length N50:	8057
Total bases:	12810

Total bases should be 8056+4682=12738. N50 should be 8056. Mean and median should be 12738/2.

**Comment by haowenz** [comment]
Note that there is '>' before the name of each read in the fasta file.

**Comment by wdecoster** [comment]
Thanks a lot for reporting this. There is an embarrassing mistake in how fasta files are handled. I never use those, so I didn't notice... 

I'll have a fix up soon.

**Comment by wdecoster** [comment]
I just pushed NanoStat v1.1.1 to PyPI, in which your issue should be solved. Thanks again!

**Comment by haowenz** [comment]
Got this error when updating. Please also see #18 

$ pip install nanostat --upgrade
Collecting nanostat
  Downloading https://files.pythonhosted.org/packages/21/1f/ceb88dc5985145d9291c41c31a7ea185350074370f26f23c9c2ac41cf445/NanoStat-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var_other/scratch/4110242.dedicated-sched.pace.gatech.edu/pip-install-2ur0s_vq/nanostat/setup.py", line 14, in <module>
        long_description=open(path.join(here, "README.md")).read(),
      File "/nv/hswarm1/hzhang639/data/miniconda3/lib/python3.6/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/var_other/scratch/4110242.dedicated-sched.pace.gatech.edu/pip-install-2ur0s_vq/nanostat/README.md'
    
    ----------------------------------------

**Comment by wdecoster** [comment]
Thanks again for reporting this. Apparently, I forgot to add the README.md to the MANIFEST.in when I started using the .md file for creating the description on PyPI. This should be solved in NanoStat v1.1.2, which I just pushed to PyPI.

Cheers,
Wouter

**Comment by haowenz** [comment]
Works now! Thanks for the quick response.
