### ISSUE TITLE
Add cram support

### ISSUE THREAD

**Issue by wdecoster** [wdecoster/nanostat#20]
Add option to get stats with --cram analogous to NanoPlot

**Comment by jvhaarst** [comment]
While you are at it, could you also add ubam support ?

**Comment by wdecoster** [comment]
That wouldn't be too hard. I'll look into it.

**Comment by wdecoster** [comment]
NanoStat v1.2.0 is now available on PyPI, and probably soon on bioconda. It has support for --ubam and --cram.

Please let me know if you have more feedback or suggestions.
