### ISSUE TITLE
Memory explosion

### ISSUE THREAD

**Issue by mbhall88** [wdecoster/nanostat#22]
I am hitting some pretty crazy memory maximums with version 1.1.2

I have a 477Mb BAM file. I ran nanostat with 8 threads and the highest peak I have hit so far for memory is 47Gb. I also get the same max. when using 1 thread...

A fastq of the same Bam file used 203Mb max.

**Comment by wdecoster** [comment]
Hmm I'll see if I can replicate this. I don't see anything odd for a single test case I just ran on a 7.3Gb bam:

![image](https://user-images.githubusercontent.com/11660522/53175749-eca06780-35ec-11e9-8bc7-bd0feb9b6af5.png)

Plot generated using mprof. I wonder if that's accurate if you're using threads though.

```
pip install memory_profiler
mprof run NanoStat --bam 20190118.bam > stats.txt
mprof plot
```

Does your bam have a lot of contigs? Or not at all?

**Comment by mbhall88** [comment]
Yes, it has **a lot** of contigs. I suspected that could be causing problems via `pysam.fetch()`?  

It's not a huge deal (I just reran with a fastq from the BAM). Just thought I would raise an issue in case others come across this too.

**Comment by wdecoster** [comment]
It's definitely misbehavior so thanks for reporting it. The number of contigs could be the cause... I don't immediately have ideas on how to solve this either. I don't really notice memory usage as I'm spoiled with a big server :-)

**Comment by wdecoster** [comment]
I think this has been solved in some changes I made quite recently, but if not let me know.
