### ISSUE TITLE
Installing without Pip/condas

### ISSUE THREAD

**Issue by crysclitheroe** [wdecoster/nanostat#24]
Good day

I work on a cluster that I don't have pip permissions rights for and doesnot have condas.

What is the next best way to install Nanostat (and nanomath, which seems to be dependency)

thanks and kind regards
crystal

**Comment by wdecoster** [comment]
What about pip with `--user`? That doesn't require any special permissions

**Comment by crysclitheroe** [comment]
Thank you @wdecoster!

**Comment by wdecoster** [comment]
Let me know if it doesn't work!
