### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [wdecoster/nanostat#25]
The conda install wasn't working for me with 
conda install nanostat
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.

pip worked just fine.

**Comment by wdecoster** [comment]
Thanks for reporting this, do you think this is specific to NanoStat or rather to conda? The error message looks rather general. Maybe @dpryan79 has seen this before?

**Comment by dpryan79** [comment]
This looks like either a channel order issue or perhaps a networking hiccup. What is the output of `conda config --show channels`?

**Comment by BenjaminSchwessinger** [comment]
I don't think it is a conda issue as I installed nanoplotter and nanoplot straight up. It appeared specific to nanostats.

conda config --show channels
channels:
  - conda-forge
  - bioconda
  - defaults

As always thanks for writing nice tools.

**Comment by dpryan79** [comment]
What else is installed in that env? That is, what is the output of `conda list`?
