### ISSUE TITLE
Error "Package setuptools conflicts " while installing NanoStat.

### ISSUE THREAD

**Issue by shashibioinfo143** [wdecoster/nanostat#26]
Hi im trying to install NanoStat in Ubuntu it shows "Package setuptools conflicts" error issue can you please help me resolve this

thanks 

conda install -c bioconda nanostat
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - nanostat -> python[version='>=3.5,<3.6.0a0,>=3.6,<3.7.0a0']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to.  Your current python version
is (python=3.7).  Note that conda will not change your python version to a different minor version
unless you explicitly specify that.

The following specifications were found to be incompatible with each other:

Package setuptools conflicts 
![error](https://user-images.githubusercontent.com/54669756/64957849-6c549300-d8ab-11e9-9b73-d051aa3ec9a9.png)
for:
python=3.7 -> pip -> wheel -> setuptools
nanostat -> nanoget[version='>=0.10.1,>=0.15.0'] -> nanomath -> pandas -> python-dateutil[version='>=2.5.*'] -> six[version='>=1.5'] -> python[version='>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools
Package wheel conflicts for:
nanostat -> nanoget[version='>=0.10.1,>=0.15.0'] -> nanomath -> pandas -> python-dateutil[version='>=2.5.*'] -> six[version='>=1.5'] -> python[version='>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel
python=3.7 -> pip -> wheel
Package pip conflicts for:
python=3.7 -> pip
nanostat -> nanoget[version='>=0.10.1,>=0.15.0'] -> nanomath -> pandas -> python-dateutil[version='>=2.5.*'] -> six[version='>=1.5'] -> python[version='>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip
Package certifi conflicts for:
nanostat -> nanoget[version='>=0.10.1,>=0.15.0'] -> nanomath -> pandas -> python-dateutil[version='>=2.5.*'] -> six[version='>=1.5'] -> python[version='>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']
python=3.7 -> pip -> wheel -> setuptools -> certifi[version='>=2016.09']

**Comment by wdecoster** [comment]
I suspect this is a problem with (bio)conda on your end, but could you try instaling NanoStat in a new environment?

```
conda install -n nanostat -c bioconda nanostat
conda activate nanostat
```

**Comment by shashibioinfo143** [comment]
Hi thanks for the quick response
I have tried the above command.
It shows error "conda not in environment /home/user/anaconda/nanostat "

**Comment by dpryan79** [comment]
@shashibioinfo143 What version of conda are you using?

**Comment by shashibioinfo143** [comment]
Hi
Conda 4.7.10 version

**Comment by wdecoster** [comment]
Hmmm, that's pretty recent so that should be fine. Have you been able to install other tools with conda?

**Comment by shashibioinfo143** [comment]
> I suspect this is a problem with (bio)conda on your end, but could you try instaling NanoStat in a new environment?
> 
> ```
> conda install -n nanostat -c bioconda nanostat
> conda activate nanostat
> ```
Hi, Thanks for the help i tried to resolve the issue and Installed successfully.

Thank you

**Comment by wdecoster** [comment]
Good to hear. How did you solve the issue, then? In case others have the same or similar problems, you can help them by sharing your solution.

**Comment by shashibioinfo143** [comment]
> Good to hear. How did you solve the issue, then? In case others have the same or similar problems, you can help them by sharing your solution.

First i tried to Create NanoStat_Env environment which i haven't done before for which it showed error message.
Then i followed the Steps of installing and activating Nanostat
