### ISSUE TITLE
Print output in wide format

### ISSUE THREAD

**Issue by flashton2003** [wdecoster/nanostat#27]
Hello,

nanostat is a nice tool, but I have lots of datasets to analyse and I'm just wishing that it could print results in wide format e.g.

![Screenshot 2019-09-18 at 14 52 23](https://user-images.githubusercontent.com/2613906/65128597-f32c7b80-da23-11e9-8c7f-d3cd5eb58690.png)

Then I could just `cat` together the outputs from multiple nanostat runs and look at the stats for multiple samples at once.

Thanks,

Phil

**Comment by wdecoster** [comment]
A solution that would not involve too many changes in the code would lead to multiple columns in long format, e.g.:

![image](https://user-images.githubusercontent.com/11660522/65131437-84d5c200-d9ff-11e9-9298-00f1f5f12067.png)

Would something like that work or not quite? It is essentially how [NanoComp](https://github.com/wdecoster/nanocomp) uses NanoStat.

Is your input data per dataset in one or multiple summary files? If the latter it gets tricky :)

**Comment by flashton2003** [comment]
That looks great, or the functionality I want might already be in NanoComp... :-)

**Comment by wdecoster** [comment]
Yes, that could be the case. Let me know if it's not what you had in mind. With NanoComp you will also get plots by default, so things will take a bit longer. If only the stats are of interest you could use NanoComp with `--plot false`.

**Comment by flashton2003** [comment]
Great, thanks!
