### ISSUE TITLE
feature request: output as tsv

### ISSUE THREAD

**Issue by kapsakcj** [wdecoster/nanostat#29]
It would be awesome if the output of NanoStat, especially when using `--barcoded` flag, could output the stats as a TSV. The current output is kind of a tsv but has headers & descriptions interspersed which makes it a little difficult to parse. Also does not play well with Microsoft Excel.

**Comment by wdecoster** [comment]
I absolutely agree. The current way of how the results are printed makes parsing hard. The code will need some changes to get to a clean TSV, and I can work on this after my holidays in two weeks. Of course, pull requests are welcome too. Perhaps it's best to add a `--tsv` option, without changing the current output for those who got used to that. The current code doesn't make me happy and invites for a more thorough refactoring :)

**Comment by kapsakcj** [comment]
Great, I'm glad you agree! If I have the time/willpower I will try to put in a PR, but I'm by no means a python expert so it will likely take me a while. I agree, a `--tsv` option sounds like the way to go, to keep the current output available

**Comment by wdecoster** [comment]
This took me longer than planned :-)

NanoStats v1.4.0 now has a --tsv argument. Similarly, NanoPlot v1.32.0 and NanoComp 1.12.0 have a --tsv_stats

Please let me know if you have additional feedback or if something doesn't work as expected.

**Comment by kapsakcj** [comment]
No worries on the wait, thanks so much for adding the feature! I'll test it out when I'm able and get back to you if anything breaks.

Cheers!

**Comment by kapsakcj** [comment]
Works like a charm and the NanoStats outputs (both nonbarcoded and --barcoded) are easily viewable in Excel. Thanks again for adding this feature 🎉 

I just made a new docker image for NanoPlot 1.32.0 which will be available on dockerhub shortly https://hub.docker.com/r/staphb/nanoplot

**Comment by kapsakcj** [comment]
one last bit of feedback - don't forget to update the READMEs here and in NanoPlot with this feature
