### ISSUE TITLE
release tags?

### ISSUE THREAD

**Issue by smoe** [wdecoster/nanostat#30]
Hi Wouter,
I thought we should round-up your portfolio of tools for the Nanopore and - guess what, I had a look a Nanostat. Would you mind adding a release tag for it?
Many thanks and best regards,
Steffen

**Comment by wdecoster** [comment]
Oh yes, thanks for letting me know! There you go: https://github.com/wdecoster/nanostat/releases/tag/1.4.0

Cheers,
Wouter
