### ISSUE TITLE
[Question] Clarification about output from bam files 

### ISSUE THREAD

**Issue by shnmunk** [wdecoster/nanostat#32]
Dear wdecoster,

It is unclear to me whether NanoStat outputs stats for i) read lengths or ii) alignment lengths using bam files as input?

And whether the stats are computed for only mapped reads or for both mapped & unmapped reads?

Thanks in advance,
Sebastian

**Comment by wdecoster** [comment]
Hi Sebastian,

With a bam file it will tell you about alignments, not about reads. So a read with a primary and a supplementary alignment will be counted twice, while secondary alignments are excluded. There is an optional flag --no_supplementary to use only primary alignments. Only mapped reads (and more specifically: mapped bases) are counted.

Cheers,
Wouter

**Comment by shnmunk** [comment]
Thanks a lot for the quick response.

Okay, so deletions or gaps introduced in e.g. a spliced alignment are not counted towards the alignment length?
Meaning that only the mapped bases for a read are summed up to compute the alignment length?

Since you did not mention it, I assume it is not possible to include secondary alignments at this point. 

- Sebastian

**Comment by wdecoster** [comment]
That's right, just the aligned bases and no gaps.

Including secondary alignments is not possible indeed. Why would that be of interest? That would be reads which you are going to count multiple times for repetitive regions?

**Comment by shnmunk** [comment]
Thanks! 

It could be of interest to explore all alignments to e.g. the transcriptome in conjunction with varying the minimap2 –p argument (minimal secondary-to-primary score ratio). But I agree it would likely not have many applications. 

I can also put this in a separate issue, but would it be possible to add a feature to NanoStat that computes the standard deviation of the mean read/alignment length since this information is used when running Salmon quantification with single-end/nanopore reads?

**Comment by wdecoster** [comment]
Adding the standard deviation would definitely be possible. I'll add it at some point, probably not today. If you feel like coding I'm happy to take a look at your pull request ;-)

**Comment by shnmunk** [comment]
That would be very useful!
I would like to, but I am fairly new to this. I hope to contribute down the line.

Cheers,
Sebastian

**Comment by wdecoster** [comment]
If you upgrade the nanomath submodule you'll now get the stdev of read length too in your stats output

**Comment by shnmunk** [comment]
Thank you!
- Sebastian
