### ISSUE TITLE
Barcoded output not available 

### ISSUE THREAD

**Issue by santoshe1** [wdecoster/nanostat#36]
Hello Wouter,

Thank you for creating this amazing tool for Nanopore statistics. I am trying to get the barcoded statistics from a sequencing_summary.txt

The command I use :-
`NanoStat --threads 20 --barcoded --tsv --summary sequencing_summary.txt -o example -n 4a`

When I use, the above command I don't find a output NanoStat_Barcoded.txt (seen in NanoPlot) or in the result out 4a - I don't see any barcoded statistics either, rather I see the total statistics of the run. However, when I print it to stdout, I see the results of barcoded statistics (in wide format).

Is there something wrong in my command or could this be a possible bug?

Tried the above using NanoStats v1.4.0 and v1.5.0.

Thank you,
-s

**Comment by wdecoster** [comment]
Hi,

Hmmm, with that command, you also don't find a file called `4a` in the `example` directory?
It seems that --barcoded does not support --tsv (for which I would need to do some more testing), but nonetheless, I don't immediately see why you wouldn't get any output file.

Wouter

**Comment by wdecoster** [comment]
Thanks for reporting this! I identified the cause, and I will have a fix online soon.

Wouter

**Comment by wdecoster** [comment]
This should be solved in NanoStat v1.6.0, which is available through pip now and through conda soon

**Comment by santoshe1** [comment]
Thank you so much for your email

**Comment by Ptero64** [comment]
Hello,
I had the same issue which has been resolved using the last version 1.6.0. However now the start of the output file (general summary to Total bases lines) are not separated by tab between barcoded samples. It is normal? I used the command --barcoded --summary -o -n and --tsv.

Thanks for the help.
