### ISSUE TITLE
how the quality score is calculated by nanostat

### ISSUE THREAD

**Issue by ShannonDaddy** [wdecoster/nanostat#37]
Hi，we found the weird quality score given by nanostat 1.5.0 which is inconsistent with our manual calculation. what's the problem here? please help us, thanks!

nanostat result:
<img width="311" alt="c991e5111584d61575823101d75199f" src="https://user-images.githubusercontent.com/6656888/146329017-9e159447-4d8b-4f1e-a61e-06645c292c82.png">

manual calculation:
<img width="659" alt="1639640678(1)" src="https://user-images.githubusercontent.com/6656888/146329177-e591f559-4794-413e-936e-5444656a2995.png">

**Comment by wdecoster** [comment]
I would like to refer you to this post on my blog:
https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/

**Comment by ShannonDaddy** [comment]
> I would like to refer you to this post on my blog: https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/

OK，thanks，I‘ll check that blog.

**Comment by wdecoster** [comment]
Feel free to let me know if you have further questions.
