### ISSUE TITLE
Nanostat report - after nanofilt I got this results:

### ISSUE THREAD

**Issue by APZPM** [wdecoster/nanostat#41]
Nanostat report - after nanofilt I got these results:
Top 5 highest mean basecall quality scores and their read lengths
1:	90.0 (108)
2:	90.0 (57)
3:	90.0 (82)
4:	90.0 (54)
5:	90.0 (50)

Do you know why?

The same reads before nanofilt gave me these results:
Top 5 highest mean basecall quality scores and their read lengths
1:	36.9 (3)
2:	33.7 (3)
3:	32.7 (7)
4:	31.0 (3)
5:	31.0 (8)

Many thanks and best regards,

Anja

**Comment by wdecoster** [comment]
Hi Anja,

You will have to give me some more information here. What is the input, and which commands did you use?
You seem to suggest that the 5 reads before nanofilt are the same as after nanofilt, but the read lengths are different. Having a read of only 3 nucleotides would be ridiculous, so I would not care about its quality. It is probably an artefact anyway, and will not contain any useful information. Having reads with a quality of 90 is also absurd - that means it is extremely high quality.

Wouter

**Comment by APZPM** [comment]
Hi again, 
so I had as the input reads before nanofil and reads after nanofilt (fastq files). Nanofilt was trimming like that --headcrop 60 --tailcrop 60 -l 50.

I just don't know from where is mean basecall quality 90?

This is the whole report before nanofilt:
General summary:        
Mean read length:                 290.8
Mean read quality:                 13.5
Median read length:               250.0
Median read quality:               13.2
Number of reads:            1,880,297.0
Read length N50:                  330.0
Total bases:              546,875,172.0
Number, percentage and megabases of reads above quality cutoffs
>Q5:	1880269 (100.0%) 546.9Mb
>Q7:	1879574 (100.0%) 546.9Mb
>Q10:	1785937 (95.0%) 520.1Mb
>Q12:	1310065 (69.7%) 372.3Mb
>Q15:	437408 (23.3%) 104.9Mb
Top 5 highest mean basecall quality scores and their read lengths
1:	36.9 (3)
2:	33.7 (3)
3:	32.7 (7)
4:	31.0 (3)
5:	31.0 (8)
Top 5 longest reads and their mean basecall quality score
1:	6090 (14.2)
2:	4876 (13.3)
3:	3806 (11.4)
4:	3386 (12.6)
5:	3329 (11.3)


And the whole report after nanofilt:

General summary:        
Mean read length:                 224.9
Mean read quality:                 13.3
Median read length:               158.0
Median read quality:               13.0
Number of reads:            1,480,407.0
Read length N50:                  271.0
Total bases:              332,941,423.0
Number, percentage and megabases of reads above quality cutoffs
>Q5:	1480402 (100.0%) 332.9Mb
>Q7:	1479526 (99.9%) 332.9Mb
>Q10:	1365530 (92.2%) 310.3Mb
>Q12:	986891 (66.7%) 220.5Mb
>Q15:	347709 (23.5%) 66.6Mb
Top 5 highest mean basecall quality scores and their read lengths
1:	90.0 (108)
2:	90.0 (57)
3:	90.0 (82)
4:	90.0 (54)
5:	90.0 (50)
Top 5 longest reads and their mean basecall quality score
1:	5970 (14.2)
2:	4756 (13.5)
3:	3686 (11.4)
4:	3266 (13.0)
5:	3209 (11.2)


Many thanks,

Anja

**Comment by wdecoster** [comment]
Well, your reads are pretty short to start with, so I don't know if cropping off 60 from both sides is really what you want. I also don't know what the goal is with this dataset? I am not sure what you want and how I can help with that. Do you need to find these reads with absurd high quality scores?
