### ISSUE TITLE
(tiny?) feature request

### ISSUE THREAD

**Issue by devonorourke** [wdecoster/nanostat#7]
Hi Wouter,
I'm using Nano{filt|lyse|plot} more and more. One thing I'm wondering about concerns the "top 5 ..." of something you generate in the NanoStat outputs... Would it be possible to include some sort of metadata character/identifier that could allow a user to parse either the .fastq or .fast5 file and search for the sequence?
As an example of why this might be useful: I've found that some times you get really long reads but they might be contaminants and I want to make sure that those reads belong to the thing you sequenced. When I see a that top 5 longest read list, it would be great to get something like the `read_id` value, which I'm guessing a quick grep search could tackle to find the sequence of interest in a .fastq file.
Thanks for your consideration,
Devon

**Comment by wdecoster** [comment]
Hi Devon,

That should be feasible, and especially if you use the albacore summary file for NanoStat. Is that the case? Extracting read_id from fastq and bam is also possible of course, but takes some more 'work'.

Cheers,
Wouter

**Comment by devonorourke** [comment]
Yep, I'm sticking with the summary file.

**Comment by wdecoster** [comment]
Okay, that makes life easier. I'll probably add your feature request in the following days.

**Comment by wdecoster** [comment]
Updating your nanomath submodule to 0.16.2 should add this, can you confirm?

**Comment by devonorourke** [comment]
Looking good. Ran the following code and generated a lightning fast output. Performed a quick grep search and confirmed the output `run_id` had a single match (and that match was indeed a long read).

Here's a snippet of the output; hoping it matches what you're expecting. Tiny suggestion: you might want to add in the output text ("_Top 5 Longest reads..._") to specify what's in the square brackets for users.
```
Top 5 longest reads and their mean basecall quality score
1:	248834 (9.3, [018f2f8e-04c5-4ff9-b945-e63c3013f7b2])
2:	211110 (10.3, [b3bee7a7-aae7-4537-8eec-984f51edd078])
3:	206837 (9.2, [032e80c2-0347-4e71-afce-19a5ddae1344])
4:	200025 (8.7, [c335dcea-f587-4080-a3a6-c6464f51d162])
5:	188631 (9.0, [e8301351-e6ba-416a-b4e9-0aaabb17b679])
Top 5 highest mean basecall quality scores and their read lengths
1:	12.9 (697, [b454ee41-1cff-44c0-a41f-4d18e2aff2c0])
2:	12.7 (715, [f9f81262-e605-4ef9-899c-df232bdcd21c])
3:	12.6 (365, [87bc1069-7e5f-43cf-8217-935c16a41703])
4:	12.6 (496, [8a93a483-a9c4-4efb-a8e8-4cef977b749e])
5:	12.5 (934, [ea9e40b3-e35b-4482-a64b-d4f1ff14441b])
```

Great work Wouter - thanks!

**Comment by wdecoster** [comment]
That's indeed what I expected. I rewrote almost the entire function for the stats report since the same code should also work for a) fastq/bam file(s) (without readIDs) and b) multiple datasets in the case of NanoComp (generates a tab-delimited table with a column per dataset).

Indeed, adding the meaning of the square brackets to the title would be good...

Thanks for the feedback and don't hesitate to post more feature requests!
