### ISSUE TITLE
"--readtype" function questions

### ISSUE THREAD

**Issue by devonorourke** [wdecoster/nanostat#8]
Hi Wouter,

If I have a project that contains both 1d and 1d2 reads in a single .fastq file, what would I do with the NanoStat `--readtype` argument? I'm guessing that the `--readtype` flag is necessary when you pass a **summary_statistics.txt** file, but probably not with a **.fastq** file.  

This leads me to the following 2.5 questions:  
- Is a `--readtype` argument necessary when passing any file or just a **summary_statistics.txt** file?    
- Do you envision a problem if I have a final **.fastq** file that is the result of merging data produced from separate library preps (say, LSK108 and LSK308) which contain 1D and 1D2 reads? I'm guessing that there might be some idiots like me who happen to have both datasets but want to plot the collective set as one nice graphic.
    - Similar as above - if I have the original two **.fastq** files from the independent library preps, I'm guessing it's not going to be an issue to run `NanoComp` without the `--readtype` flag?

Cheers,
Devon

**Comment by wdecoster** [comment]
Hi Devon,

Indeed, `--readtype` is only applicable when using a summary file. By default, it's assumed to be 1D, so you only have to change this parameter if it has to be 1D2 (or 2D for older data). The `--readtype` flag is silently ignored when you have a bam or fastq file, and that's the case for NanoPlot, NanoStat and NanoComp. I agree that this 'silent treatment' is not optimal.

I don't foresee any problems when having mixed 1D/1D2 datasets (in fastq format) for both NanoStat and NanoComp. For the parser, all fastq records should be equal.

Let me know if you see something unexpected!

Cheers,
Wouter
